### PR TITLE
fix throwing literals as exceptions

### LINKED ISSUE #405: Fix code scanning alert - disallow throwing literals as exceptions
Tracking issue for:
- [ ] https://github.com/thingweb/thingweb-playground/security/code-scanning/45

I think that another typo of error reporting is needed

### PR DESCRIPTION
**Pull request by hasanheroglu**
Closes #405

### CODE REVIEW

File: packages/web/test.js [hunk 1]
```diff
@@ -9,7 +9,8 @@ const playwright = require('playwright')
 const fs = require("fs")
 const handler = require("serve-handler")
 const http = require("http")
-const path = require("path")
+const path = require("path");
```
Comment (egekorkan) [inline packages/web/test.js:12]: the semi colon in both is actually not needed

Comment (hasanheroglu) [reply packages/web/test.js]: Fixed at [91aa76e](https://github.com/thingweb/thingweb-playground/pull/439/commits/91aa76e75dab77f00023fcd5a386a40eb1ad2d67)

**Review by egekorkan — APPROVED** [review]
